GEMENI_API_KEY="AIzaSyCKbD_wGbYLGrFVoqBzlpPUJKbbNunk9Ek"
ATLASSIAN_API_KEY="ATATT3xFfGF06NEFOOD4I5njsvDpRQ8PL4aiQimxGyv88neK8fdYYREkXjYNgwiKB63lDNvNDN81_ta_MINv2grrr-zXuvKF7JfOqRz4WMXKjKL6Yrd20GgKJuA71GbJML-x6RG-TFXQKn7SABbwvnh3ncjfk8THBv35M1ucFoHjZK4JHyelC1s=039389D8"
JIRA_BASE_URL = "https://michaelandrewglass-1751721866295.atlassian.net"
JIRA_EMAIL = "michael.andrew.glass@gmail.com"
JIRA_PROJECT_KEY = "JATP"